.travis.yml
moves code coverage to one element of the matrix only
=> Update .travis.yml (#34)

pytim/observables.py
I added the two new classes. Also corrected a few typos in the description of other classes. Also updated the description of the Profile class.
Was way easier than I thought.
=> added Mass and Charges classes

pytim/gitim.py
small fix in the multi layer gitim, to handle correctly the molecular option
=> fixed molecular + multilayer in gitim

pytim/observables.py
in observables.py :
* replaced too large internal binning
* replaced non-performant itertools.chain with numpy array operations
=> fixed sampling problem

pytim/observables.py
the radial distribution code was overwriting the position vector using a wrong group
=> small bugfix

pytim/observables.py, pytim/tests/test_observables.py
* fixed bug in profile calculation
* changed behaviour of the class: now the group has to be
passed to Profile.sample(), as with the RDF class
=> Profile class behaviour changed

docs/source/Tutorials.rst, pytim/chacon_tarazona.py, pytim/gitim.py, pytim/itim.py, pytim/willard_chandler.py
* The docstrings are formatted and indented uniformly
* The references are put in italic
* Some typos are fixed
* The following issues are fixed when generating html pages:
* ..../Pytim/docs/source/Tutorials.rst: WARNING: document isn't included in any toctree
* ..../Pytim/docs/source/Tutorials.rst: WARNING: toctree contains reference to nonexisting document u'trajectories'
=> Minor changes

pytim/profile.py
averaging of the volume over time was missing
=> fixed bug for multiple frames profile analysis

pytim/__init__.py, pytim/chacon_tarazona.py, pytim/surface.py
Minor Cleanup in Chacon-Tarazona.
This commit does not address the possible issue with the pseudoinverse in surface.py
=> Chacon tarazona

pytim/itim.py
Was able to reproduce under some conditions bug #114 
Closing open Queue() in `itim.py` seems to fix it
=> closes queues left open

docs/source/observables.rst, pytim/observables/intrinsic_distance.py, pytim/tests/test_basics.py, pytim/tests/test_dbscan.py, pytim/tests/test_observables.py, pytim/tests/test_rotation.py
Eliminate all the warnings given by Sphinx.
- Formatted the documentation
- Corrected the observables' documentation to include the Correlator
NO acutal changes in the code itself
=> Updating docs

.travis.yml, pytim/itim.py, pytim/tests/test_basics.py, setup.cfg
This test checks that nothing bad happens when using two trajectories/universes
=> added test for handling 2 trajectories

pytim/Interface.py, pytim/tests/test_basics.py
Fixed the documentation:
- writepdb() appears at the end of the ITIM/GITIM/WC/CT methods
- The Profile module is in
- Corrected the formatting
=> Fixed documentation

.travis.yml, pytim/Interface.py, pytim/__init__.py, pytim/chacon_tarazona.py, pytim/cube.py, pytim/datafiles/__init__.py, pytim/gitim.py, pytim/itim.py, pytim/observables/__init__.py, pytim/observables/basic_observables.py, pytim/observables/correlator.py, pytim/observables/orientation.py, pytim/observables/profile.py, pytim/properties.py, pytim/sanity_check.py, pytim/surface.py, pytim/tests/test_basics.py, pytim/tests/test_dbscan.py, pytim/tests/test_observables.py, pytim/tests/test_rotation.py, pytim/utilities.py, pytim/utilities_mesh.py, pytim/vtk.py, pytim/wavefront_obj.py, pytim/willard_chandler.py, setup.py
=> python 3.6

docs/source/center.rst, docs/source/guessing_radii.rst, docs/source/install.rst, docs/source/micelle.rst, docs/source/newproperties.rst, docs/source/observables.rst, docs/source/quick.rst, pytim/observables/profile.py
Fixes and cleanup in documentation and html.
=> Observables doc

pytim/Interface.py, pytim/chacon_tarazona.py, pytim/gitim.py, pytim/itim.py, pytim/willard_chandler.py
Added links to classes & formatted the docstrings.
=> Added links to classes

pytim/__init__.py
Solution of #85 
Note: this does not silence the
warning during the doctests !
=> Added filter for mass warning in MDA

pytim/examples/example_micelle.py, pytim/gitim.py
* added test with 1 atom in the cell
* added the possibility to change the buffer for PBCs from the interface
passing buffer_factor=x at init (in units of alpha)
=> gitim cleanup & fixes

pytim/observables/profile.py
Allows the user to specify the number of points used in
MC normalization when using Profile()
=> Added npoints to Profile() (for MC normalization)

pytim/observables/profile.py
=> Fix mc scale

pytim/chacon_tarazona.py, pytim/interface.py, pytim/itim.py, pytim/sanity_check.py
=> Minor cleanups

pytim/chacon_tarazona.py, pytim/vtk.py, pytim/willard_chandler.py
The Writevtk class was in willard_chandler.py
=> Moved vtk files

.travis.yml, pytim/__init__.py, pytim/itim.py, pytim/patches.py, pytim/sanity_check.py
Patches for MDtraj and OpenMM were somehow not imported correctly anymore. This patch fixes the issue and adds an MDtraj test for Travis.
=> Fix mdtraj

CHANGELOG.md, pytim/__init__.py, pytim/observables/__init__.py, pytim/observables/basic_observables.py, pytim/observables/distributionfunction.py, pytim/observables/observable.py, pytim/observables/rdf.py, pytim/observables/rdf2d.py, requirements.txt
new system for computing distribution functions
=> Distribution function

pytim/gitim.py, pytim/utilities.py
Shortened and reorganized the general linear position generation
in gitim.py
=> Minor mods in gitim.py

pytim/sasa.py
=> avoid division by zero

pytim/utilities_mesh.py
Small fix for the bug encountered in issue #333
=> cast to integer fixing numpy type error

pytim/interface.py, pytim/itim.py
Fixed the behavior of the `biggest_cluster_only` switch
=> Fix for biggest_cluster_only

pytim/itim.py
as multiproc is not available under Windows
=> ITIM: reintroduced no-multiproc

README.md, pyproject.toml, requirements.txt
=> Spec 0 badge

.github/workflows/python-package.yml, pyproject.toml, pytim/examples/example_gitim_flat.py, pytim/examples/example_mdtraj.py, pytim/examples/example_micelle.py, pytim/examples/example_openmm.py, pytim/examples/example_triangulation.py, pytim/examples/example_water-molecular-layer.py, pytim/examples/example_water.py, pytim/examples/example_willard_chandler.py, pytim/patches.py, pytim/sanity_check.py, setup.cfg
* openmm new package style supported
* reintroduced testing for mdtraj as v10.0.2 supports numpy2
* added most examples from pytim/examples to testsuite
=> Reintroduced support for Openmm. Additional tests
