- pytim/gitim.py
- pytim/itim.py
- pytim/observables.py
- pytim/wc.py
- st-dist.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Use `is` or `is not` to compare with `None`](https://www.quantifiedcode.com/app/issue_class/3IY8CZ0v)
Issue details: [https://www.quantifiedcode.com/app/project/gh:Marcello-Sega:pytim?groups=code_patterns/%3A3IY8CZ0v](https://www.quantifiedcode.com/app/project/gh:Marcello-Sega:pytim?groups=code_patterns/%3A3IY8CZ0v)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Use `is` or `is not` to compare with `None`" issue

- pytim/itim.py
- pytim/wc.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:Marcello-Sega:pytim?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:Marcello-Sega:pytim?groups=code_patterns/%3A4ACGxFj1)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality …
> Fix "Prefer `format()` over string interpolation operator" issue

- pytim/__init__.py
- pytim/chacon_tarazona.py
- pytim/gitim.py
- pytim/itim.py
- pytim/willard_chandler.py
Every surface analyzer now accepts an AtomGroup as first argument.
This AtomGroup overrides the one supplied under the group argument.
Added tests to willard-chandler and chacon-tarazona. The gitim and
itim are NOT used when
pytim setup.py test
is issued. This sould be fixed
> Patched Interface Analyzers

- pytim/tests/test_basics.py
- pytim/willard_chandler.py
Removed test from willard-chandler (as was removed from chacon-tarazona) and added a test for the interchangeability of the Universe/AtomGroup in test_basics.py
> added tests

- README.md
- pytim/__init__.py
- pytim/chacon_tarazona.py
- pytim/gitim.py
- pytim/itim.py
- pytim/observables.py
- pytim/tests/test_observables.py
- pytim/willard_chandler.py
Replaces buggy `interface.atoms` and `interface.atoms.in_layer` with new properties of the `Atom` class of `MDAnalysis`. 
It is now possible to select atoms according to which layer, side of interface, or cluster they belong to. 
* The new properties are `layers`, `sides`, `clusters`  (and the corresponding singular versions)
* The default values are -1 if the quantity has not been assigned. 
* Layers start counting from 1
* sides are 0 or 1 
* clusters can be 0 (belonging to main cluster), -1 (not assigned), 1 (belonging to smaller clusters)
Example:
import MDAnalysis as mda
import pytim 
from pytim.datafiles import WATER_GRO
u = mda.Universe(WATER_GRO)
inter = pytim.ITIM(u,max_layers=2, cluster_cut = 2.3 )
select = inter.atoms.layers == 1
print inter.atoms[select]
print …
> added new atom properties (layer, side, cluster)

- pytim/__init__.py
- pytim/itim.py
- pytim/tests/test_basics.py
This patch makes it possible to use trajectories loaded within `mdtraj` with `pytim`.
`MDAnalysis` is still required as a package to run `pytim`, but this is (almost) transparent for the user.
A basic example:
```python
import mdtraj                                    
import pytim                  
from pytim.datafiles import WATER_GRO, WATER_XTC 
t = mdtraj.load_xtc(WATER_XTC,top=WATER_GRO) 
inter = pytim.ITIM(t) 
for step in t[0:2]:
print "surface atoms:" , repr(inter.atoms.indices)
```
> Mdtraj interoperability

- setup.py
Setup.py used setuptools, cython and numpy to initialize itself, but did not check for these modules explicitly.  This modification gives clear instructions to install the missing package before running the installer.
> Fixed requirements in setup.py

- pytim/itim.py
Using example_water.py with the following line produced an error:
```python
interface = pytim.ITIM(u, alpha=2., max_layers=4, molecular=True,mesh=0.3)
```
Traceback (most recent call last):
File "example_water.py", line 11, in <module>
interface = pytim.ITIM(u, alpha=2., max_layers=4, molecular=True,multiproc=False,mesh=0.3)
File "build/bdist.macosx-10.10-x86_64/egg/pytim/itim.py", line 202, in __init__
File "build/bdist.macosx-10.10-x86_64/egg/pytim/itim.py", line 405, in _assign_layers
File "build/bdist.macosx-10.10-x86_64/egg/pytim/itim.py", line 250, in _assign_one_side
IndexError: index 28031 is out of bounds for axis 1 with size 27889
This came from the _assign_mesh() method.
A fix has been implemented along with a slightly extended documentation.
In addition:
- the unused …
> Fixed grid for ITIM

- pytim/__init__.py
- pytim/observables.py
- pytim/pdb.py
- pytim/rdf.py
- pytim/willard_chandler.py
Fixed a bunch of formatting issues and typos in the docstrings.
NOTE:
when writing docstrings:
:param int foo:        -- OK
:param int bar     :   -- NOT OK (not recognized as a parameter because of the spaces before the colon)
> Documentation

- docs/source/guessing_radii.rst
- pytim/tests/test_observables.py
- requirements.txt
- setup.py
Numpy 1.14.0 has a different output format
than 1.13.0. The doctests and the required
version is updated accordingly.
**********************************************************************
File "testsuite.rst", line 36, in default
Failed example:
print(low[0:3])
Expected:
[ 0.  1.  2.]
Got:
[0. 1. 2.]
**********************************************************************
File "testsuite.rst", line 38, in default
Failed example:
print(avg[0:3])
Expected:
[ 0.01  0.02  0.03]
Got:
[0.01 0.02 0.03]
Similarly in guessing_radii.rst ...
> Fixed error in doctests

- pytim/surface.py
in this version of intrinsic distance from a generic surface we just use the closest atom, rather than the triangulation, to calculate the distance from the surface. The previous version with the centers of the triangles led to too many (false) negative distances
> another fix for the intrinsic distance

- pytim/__init__.py
allows users to use `center_system` as a static method, without having to instantiate an interface, e.g.:
```
pytim.PYTIM.center_system('planar',u.atoms,0)
```
> some utility functions becomes available as staticmethods

- pytim/__init__.py
- pytim/chacon_tarazona.py
- pytim/gitim.py
- pytim/itim.py
- pytim/patches.py
- pytim/willard_chandler.py
passing the 'autoassign=False' option to the various PYTIM class implementations disables the automatic assignment when switching frame.
Usage example:
```
inter = pytim.GITIM(u,group=u.select_atoms('name OW'), autoassign=False)
```
> introduced option to avoid automatic interface determination

- pytim/Interface.py
- pytim/gitim.py
- pytim/tests/test_basics.py
A bulk simulation without voids larger than the probe sphere radius
does not have any surface
* previous behavior: MDAnalysis raised a ValueError
* new behavior: return empty surface groups
> allows zero surface atoms in gitim

- pytim/itim.py
in some cases `pack_into_box()` returns some negative positions (~ -1e-6). 
these are reset to zero to avoid problems with negative values passed to `cKDTree`
> fixed rare condition where pack_into_box() fails

- pytim/observables/correlator.py
- pytim/observables/profile.py
- setup.py
- Fixed math equations in docstrings
- Fixed example in profile-s:
The example on how to use the intrinsic profile was not correct.
The problem was unnoticed, because sphinx tests whole docstring blocks,
and in that context, it seemingly made sense. However, in the non-intrinsic case,
the atomgroup g was not correctly defined. 
**The HTML pages should be updated.**
- Removed duplicate code from setup.py
> Documentation2

- pytim/observables/intrinsic_distance.py
- pytim/observables/profile.py
- pytim/simple_interface.py
- pytim/surface.py
- pytim/willard_chandler.py
should fix #288 
a simple check:
import pytim
import numpy as np
from pytim.datafiles import WATER_GRO
import MDAnalysis as mda
u = mda.Universe(WATER_GRO)
u.atoms[:8].positions=np.array([[0.,0,5],[0,1,5],[1,0,5],[1,1,5],
[0.,0.,-5.],[0,1,-5],[1,0,-5],[1,1,-5]])
upper,lower=u.atoms[:4],u.atoms[4:8]
inter = pytim.SimpleInterface(u,symmetry='planar', upper=upper,
lower=lower,alpha=5.)
g = u.atoms[8:12]
g.atoms.positions=np.asarray([[.5,.5,6],[.5,.5,4],[.5,.5,-4],
[.5,.5,-6]])
print(pytim.observables.IntrinsicDistance(inter).compute(g))
[ 1. -1. -1.  1.]
"""
> flat interface intrinsic distance fix

- pytim/interface.py
MDA 0.17.0 and 0.18.0
both pack_into_box() and pack_into_box(dimensions[:3]) are OK
MDA 0.19.1
pack_into_box() is still fine, but now requires pack_into_box(dimensions)
instead of dimensions[:3].
So pack_into_box() always works.
> Cleaned up pack_into_box()

- pytim/surface.py
When instantiating an analysis such as
interface = pytim.ITIM(...)
multiple times, a memory leak occured.
This commit fixes that using a weakref.
This is to produce the error:
```
import MDAnalysis as mda 
import pytim
from pytim.datafiles import *
u = mda.Universe(WATER_GRO)
for i in range(0,2000):
print i
interface = pytim.ITIM(u, alpha=2., max_layers=4, molecular=True)
```
Here is where the error was found in ITIM:
```
for nlayer, layer in enumerate(self._layers[
0]):  # TODO should this be moved out of assign_layers?
self._surfaces[nlayer] = Surface(self, options={'layer': nlayer})
```
Which is the penultimate block in itim.py
> Fixed memory leak

- docs/source/guessing_radii.rst
- docs/source/micelle.rst
- docs/source/newproperties.rst
- docs/source/quick.rst
- pytim/sanity_check.py
The rst files in the documention use parentheses for printing.
The printing of a dictionary in sanity_check conforms to python3.
> Updated rst-s for backwards compatibility

- pytim/__init__.py
- pytim/itim.py
- pytim/patches.py
Partially fixes a problem (#320) with standard atom names replacement in MDTraj. 
If pytim is imported *before* loading a trajectory with MDTraj, the atom names replacement is suppressed, and the atom names appearing in the topology are those read from, e.g., the PDB or GRO file. If, however, the trajectory is first loaded with MDTraj, and only then pytim is imported, the atom names will still be replaced. Should be a problem (unexpected behavior) only in a small number of cases, as users tend to import modules first.
> patch for replacement tables

- pytim/vtk.py
- pytim/willard_chandler.py
The surface data outputted by Writevtk.surface contained normal vectors whose x and z axes were flipped relative to the ordering used for the surface vertices, leading to normals appearing not to be normal to the surface in visualization.
The underlying cause of this problem seems to lie in the marching_cubes_lewiner function from skimage, in which the axes are flipped for both vertices and normals because (according to a comment in the code) "skimage uses zyx ordering"...
Fixed by flipping the axes back after the call to marching_cubes.
> flipped x and z axes in marching_cubes output for consistency

- pytim/interface.py
- pytim/willard_chandler.py
See #390 
The Willard-Chandler method does not identify surface atoms or layers, so these are now set to empty atom groups. An additional comment has been added to the documentation.
> FIX: set empty atom groups for WC
